from tools.system_tools import (
    open_app, close_app, run_command, take_screenshot, wait, respond,
    copy_to_clipboard, get_clipboard,
    set_volume, mute_volume, volume_up, volume_down,
    get_system_info, get_battery, get_cpu_usage, get_ram_usage,
    get_disk_usage, get_running_processes, kill_process,
    create_file, read_file, delete_file, list_files,
    move_file, copy_file, zip_files, unzip_file, find_files, get_file_info,
    get_ip_address, ping, get_wifi_info, get_network_speed,
    lock_screen, shutdown, restart, sleep_pc,
    show_notification, set_wallpaper,
    press_key, type_text,
    get_datetime, set_reminder, calculate,
    search_in_file, word_count,
    get_screen_resolution, empty_recycle_bin, get_env_var, set_brightness,
    get_installed_apps, open_task_manager, clear_temp_files, get_startup_programs,
    rename_file, append_to_file, get_mouse_position, move_mouse,
    mouse_click, mouse_double_click, right_click, scroll_mouse,
)
from tools.browser_tools import (
    open_website, search_youtube, click_first_video,
    search_google, search_bing, search_amazon,
    click, click_button, type, clear_and_type,
    press_enter, press_escape,
    scroll, scroll_to_top, scroll_to_bottom,
    fill_form, scrape, get_table_data, send_email,
    go_back, go_forward, refresh_page,
    get_current_url, get_page_title, get_page_text, get_links,
    zoom_page, take_browser_screenshot, take_full_page_screenshot,
    wait_for_element, hover, select_option,
    open_youtube, open_gmail, open_github,
    open_google_maps, open_google_translate, open_wikipedia,
    open_new_tab, close_browser, download_file,
    search_duckduckgo, open_twitter, open_reddit, open_linkedin,
    open_stackoverflow, open_netflix, open_spotify_web,
    get_page_screenshot_base64, highlight_element, count_elements,
    get_element_text, open_incognito,
)
from tools.api_tools import (
    get_weather, get_weather_detailed, get_news,
    get_crypto_price, get_currency_rate, get_stock_price,
    define_word, translate_text, get_synonyms,
    get_joke, get_quote, get_fact,
    get_time_in_city, shorten_url, get_qr_code,
    search_wikipedia, get_github_user,
    api_get, api_post, check_website_status,
    get_ip_info, get_moon_phase, get_nasa_apod, get_random_dog, get_random_cat,
    get_country_info, get_holidays, get_air_quality, uuid_generate,
    get_color_info, get_advice, get_trivia,
    generate_password, summarize_text, get_forex_rates, get_earthquake_data,
    get_number_fact, get_word_of_day, get_chuck_norris_joke, get_dad_joke,
    get_news_by_category, get_daily_digest, get_breaking_news, get_news_articles,
)
from tools.camera_tools import open_camera, click_photo, close_camera, record_video, get_camera_info
from tools.desktop_tools import (
    focus_window, list_open_windows, close_window, maximize_window, minimize_window,
    hotkey, desktop_type, desktop_press, desktop_click, desktop_double_click,
    desktop_right_click, desktop_scroll, select_all, copy, paste, undo, save_file, new_file,
    calculator_compute, notepad_write, notepad_save_as,
    open_website_visible, search_google_visible, search_youtube_visible, click_first_video_visible,
    search_duckduckgo_visible, open_youtube_visible, open_gmail_visible, open_github_visible,
    open_google_maps_visible, open_google_translate_visible, open_wikipedia_visible,
    open_twitter_visible, open_reddit_visible, open_linkedin_visible, open_stackoverflow_visible,
    open_netflix_visible, open_spotify_web_visible, open_incognito_visible,
    app_type_and_enter, open_and_type, search_in_start_menu, open_run_dialog,
    switch_window, show_desktop, take_desktop_screenshot, get_screen_size, get_mouse_pos,
)


class ToolRegistry:
    def __init__(self):
        self._tools: dict = {}
        self._register()

    def _register(self):
        self._tools = {
            # System
            "open_app":             open_app,
            "close_app":            close_app,
            "run_command":          run_command,
            "take_screenshot":      take_screenshot,
            "wait":                 wait,
            "respond":              respond,
            "get_system_info":      get_system_info,
            "get_battery":          get_battery,
            "get_cpu_usage":        get_cpu_usage,
            "get_ram_usage":        get_ram_usage,
            "get_disk_usage":       get_disk_usage,
            "get_running_processes":get_running_processes,
            "kill_process":         kill_process,
            "lock_screen":          lock_screen,
            "shutdown":             shutdown,
            "restart":              restart,
            "sleep_pc":             sleep_pc,
            "show_notification":    show_notification,
            "set_wallpaper":        set_wallpaper,
            "get_datetime":         get_datetime,
            "set_reminder":         set_reminder,
            "calculate":            calculate,
            "get_screen_resolution":get_screen_resolution,
            "empty_recycle_bin":    empty_recycle_bin,
            "get_env_var":          get_env_var,
            "set_brightness":       set_brightness,
            "get_installed_apps":   get_installed_apps,
            "open_task_manager":    open_task_manager,
            "clear_temp_files":     clear_temp_files,
            "get_startup_programs": get_startup_programs,
            "rename_file":          rename_file,
            "append_to_file":       append_to_file,
            "get_mouse_position":   get_mouse_position,
            "move_mouse":           move_mouse,
            "mouse_click":          mouse_click,
            "mouse_double_click":   mouse_double_click,
            "right_click":          right_click,
            "scroll_mouse":         scroll_mouse,
            # Clipboard
            "copy_to_clipboard":    copy_to_clipboard,
            "get_clipboard":        get_clipboard,
            # Volume
            "set_volume":           set_volume,
            "mute_volume":          mute_volume,
            "volume_up":            volume_up,
            "volume_down":          volume_down,
            # Files
            "create_file":          create_file,
            "read_file":            read_file,
            "delete_file":          delete_file,
            "list_files":           list_files,
            "move_file":            move_file,
            "copy_file":            copy_file,
            "zip_files":            zip_files,
            "unzip_file":           unzip_file,
            "find_files":           find_files,
            "get_file_info":        get_file_info,
            "search_in_file":       search_in_file,
            "word_count":           word_count,
            # Network
            "get_ip_address":       get_ip_address,
            "ping":                 ping,
            "get_wifi_info":        get_wifi_info,
            "get_network_speed":    get_network_speed,
            # Keyboard
            "press_key":            press_key,
            "type_text":            type_text,
            # Browser
            # Force visible browser automation for core browse/search/play actions.
            "open_website":         open_website_visible,
            "search_youtube":       search_youtube_visible,
            "click_first_video":    click_first_video_visible,
            "search_google":        search_google_visible,
            "search_bing":          search_bing,
            "search_amazon":        search_amazon,
            "open_youtube":         open_youtube_visible,
            "open_gmail":           open_gmail_visible,
            "open_github":          open_github_visible,
            "open_google_maps":     open_google_maps_visible,
            "open_google_translate":open_google_translate_visible,
            "open_wikipedia":       open_wikipedia_visible,
            "click":                click,
            "click_button":         click_button,
            "type":                 type,
            "clear_and_type":       clear_and_type,
            "press_enter":          press_enter,
            "press_escape":         press_escape,
            "scroll":               scroll,
            "scroll_to_top":        scroll_to_top,
            "scroll_to_bottom":     scroll_to_bottom,
            "fill_form":            fill_form,
            "scrape":               scrape,
            "get_table_data":       get_table_data,
            "send_email":           send_email,
            "go_back":              go_back,
            "go_forward":           go_forward,
            "refresh_page":         refresh_page,
            "get_current_url":      get_current_url,
            "get_page_title":       get_page_title,
            "get_page_text":        get_page_text,
            "get_links":            get_links,
            "zoom_page":            zoom_page,
            "take_browser_screenshot": take_browser_screenshot,
            "take_full_page_screenshot": take_full_page_screenshot,
            "wait_for_element":     wait_for_element,
            "hover":                hover,
            "select_option":        select_option,
            "open_new_tab":         open_new_tab,
            "close_browser":        close_browser,
            "download_file":        download_file,
            "search_duckduckgo":    search_duckduckgo_visible,
            "open_twitter":         open_twitter_visible,
            "open_reddit":          open_reddit_visible,
            "open_linkedin":        open_linkedin_visible,
            "open_stackoverflow":   open_stackoverflow_visible,
            "open_netflix":         open_netflix_visible,
            "open_spotify_web":     open_spotify_web_visible,
            "get_page_screenshot_base64": get_page_screenshot_base64,
            "highlight_element":    highlight_element,
            "count_elements":       count_elements,
            "get_element_text":     get_element_text,
            "open_incognito":       open_incognito_visible,
            # API
            "get_weather":          get_weather,
            "get_weather_detailed": get_weather_detailed,
            "get_news":             get_news,
            "get_crypto_price":     get_crypto_price,
            "get_currency_rate":    get_currency_rate,
            "get_stock_price":      get_stock_price,
            "define_word":          define_word,
            "translate_text":       translate_text,
            "get_synonyms":         get_synonyms,
            "get_joke":             get_joke,
            "get_quote":            get_quote,
            "get_fact":             get_fact,
            "get_time_in_city":     get_time_in_city,
            "shorten_url":          shorten_url,
            "get_qr_code":          get_qr_code,
            "search_wikipedia":     search_wikipedia,
            "get_github_user":      get_github_user,
            "api_get":              api_get,
            "api_post":             api_post,
            "check_website_status": check_website_status,
            "get_ip_info":          get_ip_info,
            "get_moon_phase":       get_moon_phase,
            "get_nasa_apod":        get_nasa_apod,
            "get_random_dog":       get_random_dog,
            "get_random_cat":       get_random_cat,
            "get_country_info":     get_country_info,
            "get_holidays":         get_holidays,
            "get_air_quality":      get_air_quality,
            "uuid_generate":        uuid_generate,
            "get_color_info":       get_color_info,
            "get_advice":           get_advice,
            "get_trivia":           get_trivia,
            "generate_password":    generate_password,
            "summarize_text":       summarize_text,
            "get_forex_rates":      get_forex_rates,
            "get_earthquake_data":  get_earthquake_data,
            "get_number_fact":      get_number_fact,
            "get_word_of_day":      get_word_of_day,
            "get_chuck_norris_joke":get_chuck_norris_joke,
            "get_dad_joke":         get_dad_joke,
            "get_news_by_category": get_news_by_category,
            "get_daily_digest":     get_daily_digest,
            "get_breaking_news":    get_breaking_news,
            # Camera
            "open_camera":          open_camera,
            "click_photo":          click_photo,
            "close_camera":         close_camera,
            "record_video":         record_video,
            "get_camera_info":      get_camera_info,
            # Desktop Automation
            "focus_window":         focus_window,
            "list_open_windows":    list_open_windows,
            "close_window":         close_window,
            "maximize_window":      maximize_window,
            "minimize_window":      minimize_window,
            "hotkey":               hotkey,
            "desktop_type":         desktop_type,
            "desktop_press":        desktop_press,
            "desktop_click":        desktop_click,
            "desktop_double_click": desktop_double_click,
            "desktop_right_click":  desktop_right_click,
            "desktop_scroll":       desktop_scroll,
            "select_all":           select_all,
            "copy":                 copy,
            "paste":                paste,
            "undo":                 undo,
            "save_file":            save_file,
            "new_file":             new_file,
            "calculator_compute":   calculator_compute,
            "notepad_write":        notepad_write,
            "notepad_save_as":      notepad_save_as,
            "app_type_and_enter":   app_type_and_enter,
            "open_and_type":        open_and_type,
            "search_in_start_menu": search_in_start_menu,
            "open_run_dialog":      open_run_dialog,
            "switch_window":        switch_window,
            "show_desktop":         show_desktop,
            "take_desktop_screenshot": take_desktop_screenshot,
            "get_screen_size":      get_screen_size,
            "get_mouse_pos":        get_mouse_pos,
        }

    def get(self, name: str):
        return self._tools.get(name)

    def register(self, name: str, fn):
        self._tools[name] = fn

    def list_tools(self) -> list:
        groups = {
            "System":   ["open_app","close_app","run_command","take_screenshot","wait","respond",
                         "get_system_info","get_battery","get_cpu_usage","get_ram_usage","get_disk_usage",
                         "get_running_processes","kill_process","lock_screen","shutdown","restart",
                         "sleep_pc","show_notification","set_wallpaper","get_datetime","set_reminder","calculate",
                         "get_screen_resolution","empty_recycle_bin","get_env_var","set_brightness",
                         "get_installed_apps","open_task_manager","clear_temp_files","get_startup_programs"],
            "Clipboard":["copy_to_clipboard","get_clipboard"],
            "Volume":   ["set_volume","mute_volume","volume_up","volume_down"],
            "Files":    ["create_file","read_file","delete_file","list_files","move_file","copy_file",
                         "zip_files","unzip_file","find_files","get_file_info","search_in_file","word_count",
                         "rename_file","append_to_file"],
            "Network":  ["get_ip_address","ping","get_wifi_info","get_network_speed"],
            "Keyboard": ["press_key","type_text"],
            "Mouse":    ["get_mouse_position","move_mouse","mouse_click","mouse_double_click","right_click","scroll_mouse"],
            "Browser":  ["open_website","search_youtube","click_first_video","search_google","search_bing",
                         "search_amazon","open_youtube","open_gmail","open_github","open_google_maps",
                         "open_google_translate","open_wikipedia","click","click_button","type",
                         "scroll","scroll_to_top","scroll_to_bottom","fill_form","scrape","get_table_data",
                         "send_email","go_back","go_forward","refresh_page","get_current_url","get_page_title",
                         "get_page_text","get_links","zoom_page","take_browser_screenshot",
                         "take_full_page_screenshot","wait_for_element","hover","select_option",
                         "open_new_tab","close_browser","download_file",
                         "search_duckduckgo","open_twitter","open_reddit","open_linkedin",
                         "open_stackoverflow","open_netflix","open_spotify_web",
                         "get_page_screenshot_base64","highlight_element","count_elements",
                         "get_element_text","open_incognito"],
            "API":      ["get_weather","get_weather_detailed","get_news","get_crypto_price","get_currency_rate",
                         "get_stock_price","define_word","translate_text","get_synonyms","get_joke","get_quote",
                         "get_fact","get_time_in_city","shorten_url","get_qr_code","search_wikipedia",
                         "get_github_user","api_get","api_post","check_website_status",
                         "get_ip_info","get_moon_phase","get_nasa_apod","get_random_dog","get_random_cat",
                         "get_country_info","get_holidays","get_air_quality","uuid_generate",
                         "get_color_info","get_advice","get_trivia",
                         "generate_password","summarize_text","get_forex_rates","get_earthquake_data",
                         "get_number_fact","get_word_of_day","get_chuck_norris_joke","get_dad_joke",
                         "get_news_by_category","get_daily_digest","get_breaking_news"],
            "Camera":   ["open_camera","click_photo","close_camera","record_video","get_camera_info"],
            "Desktop":  ["focus_window","list_open_windows","close_window","maximize_window","minimize_window",
                         "hotkey","desktop_type","desktop_press","desktop_click","desktop_double_click",
                         "desktop_right_click","desktop_scroll","select_all","copy","paste","undo",
                         "save_file","new_file","calculator_compute","notepad_write","notepad_save_as",
                         "app_type_and_enter","open_and_type","search_in_start_menu","open_run_dialog",
                         "switch_window","show_desktop","take_desktop_screenshot","get_screen_size","get_mouse_pos"],
        }
        return [{"name": k, "group": g}
                for g, names in groups.items()
                for k in names if k in self._tools]
